01 cli
vasalf/hse-software-design-homework pull request #1
Opened 2019-02-05 23:35 UTC by vasalf

2019-02-25 11:15 UTC, yurii-litvinov requested changes
```
x=ex
y=it
$x"$y"
```
работает как exit (вполне ок)
```
$x$y
```
понимается как `ex$y` и говорит `command not found` (ожидался выход)
```
$x $y
```
намертво вешает шелл (ожидалось command not found)

Всё остальное работает, архитектура адекватна, замечаний по коду вообще нет. Может, потому, что я давно на плюсах не программировал, но мне кажется, что всё круто (TTokenizeDFA особенно зачотен). В общем, 19 баллов из 21 (+балл за чрезвычайную аккуратность и обстоятельность).

2019-02-25 11:15 UTC, yurii-litvinov commented on cli/README.md
> +It creates the needed number of streams and executes the commands subsequently.
:+1:

2019-02-25 11:15 UTC, yurii-litvinov commented on cli/lib/environment/environment.cpp
> +    for (const char** varval = envp; *varval != nullptr; varval++) {
varval выглядит странно. camelCase же

2019-03-29 18:28 UTC, vasalf commented
Я повторю то, что я говорил на паре лично про пример с `ex it`: шелл вешается потому, что `ex` — это древний никсовый текстовый редактор, существующий на многих системах. Шелл вешается, потому что он в этом окружении запуститься не может (вероятнее всего, каких-то фич для curses в шелле не хватает).

Остальное я поправил.

2019-03-29 19:41 UTC, yurii-litvinov approved these changes
Да, теперь всё ок, зачтена

2019-03-31 08:51 UTC, merged