Lab4
vasalf/hse-software-design-homework pull request #5
Opened 2019-02-18 12:51 UTC by myutman

2019-02-18 13:55 UTC, vasalf approved these changes

2019-02-20 00:16 UTC, myutman commented
Очень подобно расписанная архитектура и инструкции по сборке, что существенно облегчило работу по добавлению двух новых команд.
Правда сначала не очень было понятно, какой из двух интерфейсов надо реализовывать, потому что часть из имевшихся команд реализовала один интерфейс, а часть -- другой, но, по смыслу, вроде бы, стало понятно.
С добавлением тестов проблем не возникло.

2019-03-27 14:26 UTC, yurii-litvinov requested changes
Внешние команды ничего не знают про cd. Простой способ воспроизвести --- сделать cd .. несколько раз и git status.

2019-03-27 14:26 UTC, yurii-litvinov commented on cli/lib/executor/private/builtin_executors.cpp
> +        std::cerr << "ls: Too many arguments" << std::endl;
ls --- последствия копипаста :) Должно быть cd, как я понимаю

2019-03-31 08:56 UTC, merged